### ISSUE TITLE
TASTY_ACCEPT=True doesn't work

### ISSUE THREAD

**Issue by feuerbach** [feuerbach/tasty-golden#17]
I suspect this is because the command line parser always yields a value, one way or the other...

Need to fix this, and investigate what other options (outside of this package) may be affected.

**Comment by wincent** [comment]
Came here to report this.

For now, the workaround I am using is to just delete any golden file that I want to update and then re-run, at which point it gets auto-created.

**Comment by feuerbach** [comment]
@wincent oh that sucks. Why can't you use `--accept`?

**Comment by wincent** [comment]
I am not using the runner, instead running the suite via `cabal test` (which may be a novice mistake in itself as this is my first proper Haskell project and I understand Stack is gaining favor over Cabal now).

So the workaround is not so bad. I end up doing something like:

```
cabal test # inspect diff, visible thanks to `goldenVsStringDiff`
rm tests/fixtures/*.golden # (if diff looks good)
cabal test
```

Whereas if `TASTY_ACCEPT` worked I would do:

```
cabal test
TASTY_ACCEPT=True cabal test
```

**Comment by feuerbach** [comment]
You should be able to pass normal command line options like this: `cabal test --test-options=--accept`. 

Likewise, if/when you move to stack (which I highly recommend), you can say `stack --test-arguments=--accept`.

I hope to get around to fixing this issue in April, but until that, there's no need to suffer and remove files by hand :)

**Comment by wincent** [comment]
Ah sweet... Thanks for the tip.
