### ISSUE TITLE
Compilation error since 2.3.1.1

### ISSUE THREAD

**Issue by lalo** [feuerbach/tasty-golden#19]
```
  Test\Tasty\Golden\Internal.hs:38:7:
         
             Not in scope: `<>'
         
             Perhaps you meant one of these:
         
               `<$>' (imported from Options.Applicative),
         
               `*>' (imported from Options.Applicative),
         
               `<$' (imported from Options.Applicative)
```

What am I missing? Do we need to add import Data.Semigroup per https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Semigroup.html ?

**Comment by feuerbach** [comment]
I think you're getting this error from an earlier version, not 2.3.1.1. In 2.3.1.1 this error has been fixed. Could you double-check?

**Comment by lalo** [comment]
It looks like you are right, weird that I just saw this right when you released the update. Thanks for the help and for Tasty.
