### ISSUE TITLE
Use Diff instead of (or in addition to) the external diff command

### ISSUE THREAD

**Issue by achudnov** [feuerbach/tasty-golden#2]
There's a native Haskell implementation of the diff algorithm in package [Diff](http://hackage.haskell.org/package/Diff). For portability, it would be great to be able to use that implementation instead of relying on external tools. If you're interested, I can submit a pull request with an implementation.

**Comment by sapek** [comment]
Is anyone working on this? Portable diff is a pretty important feature for a golden test framework.

**Comment by feuerbach** [comment]
Not as far as I can tell. Feel free to dig in.

**Comment by sapek** [comment]
I'm currently using `Data.Algorithm.DiffContext` and `Text.PrettyPrint` to display diffs, something along these lines (taken out of context but you get the idea):

``` haskell

diff :: BytesString -> ByteString -> String
diff x y = render $ prettyContextDiff
                            (text golden)
                            (text "test output")
                            (text . BS.unpack)
                            (getContextDiff 3 (BS.lines x) (BS.lines y))
```

I think a question before was about converting `ByteString` to `String` in order to display it. Currently `goldenVsString` uses `show` but it is not always the best choice because it will escape `"` for example. I'm not sure there is one covertion that is always right. What do you think about leaving it to the user just like [`prettyContextDiff`](http://hackage.haskell.org/package/Diff-0.3.2/docs/Data-Algorithm-DiffContext.html) does?

``` haskell

goldenVsStringDiff
    :: TestName	
    -> FilePath	
    -> IO ByteString	
    -> (ByteString -> Doc)
    -> TestTree

```

**Comment by feuerbach** [comment]
It could be left for the user as long as we provide a sensible function to plug in there -- something along the lines that I described above. show is not a sensible function in this context.

**Comment by sapek** [comment]
Simply `BS.unpack` should work for ASCII text files (using `ByteString.Char8`). For files in specific encoding there are several [`ByteString -> Text`](https://www.haskell.org/hoogle/?hoogle=ByteString+-%3E+Text) functions that could be used before converting `Text` to `String`.

**Comment by feuerbach** [comment]
I was talking about binary files.

**Comment by sapek** [comment]
The diff is line-wise so it doesn't make sense for binary files anyways.

**Comment by feuerbach** [comment]
Ok, fair enough.

**Comment by libscott** [comment]
Just a side note, currently if you use `["colordiff", "-u", ref, new]` as your diff command you get a nice colorized diff in the test output :smile:. It's indented which looks a bit weird, but otherwise it looks really good.

**Comment by michaelpj** [comment]
I'm interested in picking this up. @sapek I notice you have some commits in your fork moving towards this - do you mind if I build off them?

**Comment by sapek** [comment]
That would be great. I haven't tried my changes with the current code but hopefully they are still somewhat relevant.
