### ISSUE TITLE
Missing example in documentation

### ISSUE THREAD

**Issue by alexanderkjeldaas** [feuerbach/tasty-golden#20]
The haddock documentation should probably include a minimal, typical example.

**Comment by asr** [comment]
Yes! Please include an example.

**Comment by feuerbach** [comment]
Hi, I have now published an [introductory blog post](https://ro-che.info/articles/2017-12-04-golden-tests) containing a simple example and linked to it in the docs. Let me know if this is what you asked for.

I suppose I could add a trivial example to the haddocks, something like

```
import Test.Tasty (defaultMain, TestTree, testGroup)
import Test.Tasty.Golden (goldenVsString, findByExtension)
import Data.ByteString.Lazy.Char8 as LBS8

main :: IO ()
main = defaultMain $ goldenVsString
  "2+2" -- test name
  "example.txt" -- golden file path
  (return . LBS8.pack . show $ 2+2) -- action to produce the result
```

but I'm not sure this would be helpful.

**Comment by asr** [comment]
Thanks for writing the introductory blog post. 

+1 for explicitly importing the identifiers.

**Comment by feuerbach** [comment]
Released an update that links to the blog post.
