### ISSUE TITLE
Add a flag to fail if no file exists

### ISSUE THREAD

**Issue by brandon-leapyear** [feuerbach/tasty-golden#22]
It would be nice to have a flag that would fail the test suite if a goldens file doesn't exist. This is for CI, so that developers don't accidentally merge a PR while forgetting to include the goldens files.

**Comment by feuerbach** [comment]
Makes sense. Would you like to prepare a PR? I don't know when I'll get around to this.

**Comment by feuerbach** [comment]
Done in #23
