### ISSUE TITLE
Are the golden and out file paths expected to be different?

### ISSUE THREAD

**Issue by philderbeast** [feuerbach/tasty-golden#26]
For the documentation of `goldenVsFile`, about the golden and out file, can we say what the behaviour is if these paths are the same? Are they expected to be different?

https://github.com/feuerbach/tasty-golden/blob/6bb413bccf7bb5c400e188599b2393bc002c5b04/Test/Tasty/Golden.hs#L78-L79

**Comment by feuerbach** [comment]
Well, it is the difference between those two files that indicates a test failure. If you give it the same file path, then your test will always pass. So yeah, those paths will typically be different.
