### ISSUE TITLE
Capture and compare exceptions as test output

### ISSUE THREAD

**Issue by eddiew** [feuerbach/tasty-golden#28]
If I expect a test to fail, currently I have to use `expectFail` from `tasty-expected-failure`. This works, but it doesn't let me match the exception type, and (imo) it pollutes the style of my golden tests by putting the expected result in the code, instead of in a data file.

We can test for expected failures instead by catching exceptions and storing the serialized exception in the golden file. If a test throws an exception, now the framework can compare the serialized exception with what is expected to see if the correct exception was thrown.

Thoughts?

**Comment by feuerbach** [comment]
I usually solve this by applying try and using the result (of type `Either SomeException a`) as the golden file contents (e.g. via the Show instance).

**Comment by eddiew** [comment]
Oh that's a good solution. I ended up writing a wrapper for my own tests to automatically do this.
