### ISSUE TITLE
multiple "gold" files

### ISSUE THREAD

**Issue by LeventErkok** [feuerbach/tasty-golden#30]
Thanks for tasty-golden! It's such a productivity boost.

I have a use case where the action can generate both a "stdout" and a "stderr." So, in a sense each of my tests have two golden output files. Usually, one of these will be empty; but let's say we can have N golden files per test.

What's a good way to deal with this in tasty-golden? The main API seems to allow for only one golden-file per test; is there some cunning trick (or another tasty ingredient perhaps?) that allows for N-gold-files scenario?

**Comment by feuerbach** [comment]
Glad you like it!

The cleanest way would probably be just to add such a function (and express the existing ones in terms of it). If you're willing to do this, I'd accept a PR.

Other than that, I see a couple of workarounds:

1. Just serialize them together in a single file. The format could be as stupid as
   ```
   <stdin>
   -------
   <stdout>
   ```

   While it is theoretically possible that two different (stdin, stdout) combinations result in the same serialized file, I'm guessing it won't be a huge concern in a test suite. Or you could come up with a more complicated but reversible serialization format.

2. Wrap the actual computation in [withResource](https://hackage.haskell.org/package/tasty-1.2.3/docs/Test-Tasty.html#g:5) and have one golden test per file that will grab the resource and serialize the corresponding portion of it to the file.

**Comment by LeventErkok** [comment]
`withSource` seems like a good approach. Thanks for the advice!
