### ISSUE TITLE
*Diff functions do not create golden files when they are missing

### ISSUE THREAD

**Issue by feuerbach** [feuerbach/tasty-golden#32]
I think the easiest way to fix would be try to stat the file before calling the external program, so that an appropriate exception is raised (and handled by runGolden).

**Comment by RyanGlScott** [comment]
Is it really all `*Diff` functions that exhibit this bug, or just `goldenVsFileDiff`? Judging from the program below at least, it appears that `goldenVsStringDiff` creates missing golden files correctly:

```hs
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Test.Tasty
import Test.Tasty.Golden

main :: IO ()
main = defaultMain $
  testGroup "Group"
    [ goldenVsStringDiff "Test1" diff "test1.golden" (return "")
    , goldenVsFileDiff   "Test2" diff "test2.golden" "test2.actual" (return ())
    ]
  where
    diff ref new = ["diff", "-w", "-B", ref, new]
```
```
λ> :main
Group
  Test1: OK
    Golden file did not exist; created
  Test2: diff: test2.golden: No such file or directory
FAIL

1 out of 2 tests failed (0.00s)
*** Exception: ExitFailure 1
```

I definitely agree that `goldenVsFileDiff` is broken in this regard, however. I've submitted #38 with a fix.
