### ISSUE TITLE
Provide flag to disable cutoff

### ISSUE THREAD

**Issue by RyanGlScott** [feuerbach/tasty-golden#34]
As of version 2.3.3, `tasty-golden` truncates test output that is larger than `size-cutoff` bytes. I find this behavior to be unhelpful most of the time, since I regularly look at large `tasty-golden` diffs to determine if some code that I'm in the process of writing actually works correctly. To make things more annoying, I then have to repeatedly guess a sufficiently large `size-cutoff` value until I find one that is large enough to actually display the entire diff.

Would you be willing to consider a flag that toggles the cutoff behavior on or off? I'd be fine with keeping the cutoff behavior as the default so long as I have the ability to turn it off.

**Comment by feuerbach** [comment]
Hi Ryan,

My original intent was that you could effectively disable size-cutoff by providing some ridiculously large value like 9223372036854775807 (`= maxBound :: Int64`).

But I don't think most people want to go even that extreme. Would you really want tasty-golden to print a 10GB diff if it came to it? So you could put `TASTY_SIZE_CUTOFF=10000000000` in your `~/.profile` and forget about this feature unless/until something goes terribly wrong.

I don't think a separate option is worth it, to be honest. If none of the above persuades you, I'd be open to a patch interpreting 0, -1, `""` or some similar magic value as an off switch.

**Comment by RyanGlScott** [comment]
Alright, I think I can live with simply defining `TASTY_SIZE_CUTOFF=10000000000`. Thanks for the quick response.

**Comment by georgefst** [comment]
For anyone else who comes across this and assumes `TASTY_SIZE_CUTOFF` is the only workaround, note that since Version 2.3.3, there is also a CLI flag `--size-cutoff`.

**Comment by UnkindPartition** [comment]
Right, I mentioned the environment variable just because you can put it in your `~/.profile` and forget about it, whereas a command option needs to be passed explicitly. In general (with very few exceptions), any tasty option can be set via command line, an environment variable, or in the code: https://github.com/UnkindPartition/tasty#setting-options

**Comment by georgefst** [comment]
> any tasty option can be set via command line, an environment variable, or in the code

Thanks! I wasn't aware of that.
