### ISSUE TITLE
Remove successful test output

### ISSUE THREAD

**Issue by jrp2014** [feuerbach/tasty-golden#39]
Thanks for this package.   Just the job!

It would be useful to delete the output from successful tests as the tests are run.  In my case I have 3-4 different outputs for a test based on a single input run with different configuration parameters.  The output directory gets clogged with output that is identical to the golden files, making it harder to focus on the unsuccessful cases.

There are various workarounds, but they are ugly, as each output filename is a function of the test parameters.

**Comment by feuerbach** [comment]
Yeah, I think we could introduce such an option (as in a tasty option, not an extra argument to goldenVsFile, as that would be a breaking change). Feel free to submit a PR.

**Comment by jrp2014** [comment]
Thanks.  Yes, I figured that that would be the case.  Any suggestions as to broad steps, to reduce the time I need to get my head around Options, Ingredients, TestReporters and Managers, Providers, Runners...?

I assume that I need to add an Option and modify one or more of the bits of Tasty that actually run a test, but any pointers welcome.

**Comment by feuerbach** [comment]
I don't think you need to touch tasty itself, only tasty-golden. There are already options defined in Test.Tasty.Golden.Internal, you can use one of them (like `NoCreateFile`) as an example and add your own. Make sure to add it to the `instance IsTest Golden`.

Then add a new field to Golden to remove the file and call it in `runGolden` when appropriate.

To avoid breaking existing code, we can keep the type of `goldenTest` as is, and introduce `goldenTest2` that additionally takes the action to delete the output. It looks like we don't export the underlying Golden type, so we'll avoid any breaking changes this way.

**Comment by feuerbach** [comment]
Fixed by #40.
