### ISSUE TITLE
Option for handling tests that intentionally produce no output file

### ISSUE THREAD

**Issue by jrp2014** [feuerbach/tasty-golden#41]
An option that I'd find useful is to be able to declare a test passed (or failed) if it generates no output file.

I have a source code transformation plug-in that attempts not to touch the input file if the transformation turns out to be an identity (otherwise the modify date of the file is changed unnecessarily) and so generates no output file.

At present `tasty-golden` throws an IO error, as expected, and the test fails.  

It is, of course, possible to just write a dummy test output file before running the test and make that the golden file, but it would not be hard to add a (non-default) option for `tasty-golden` that passed tests that had no golden file and produced no output. 

I seem to remember reading somewhere that this was what the main `tasty` framework assumes that IO errors are just thrown, so there may be a way of doing this already but, if not, it would be good to have the facility to control the outcome of a test when there is no output file specifically (as distinct from permissions or other IO errors).

**Comment by feuerbach** [comment]
I think you can achieve this yourself by using `goldenTest` and playing with the "get the tested value" and "comparison function" components. (E.g. map the absent output file to Nothing, and make it always pass the test.)

This looks like an overly specialized to add an option for it.
