### ISSUE TITLE
Struggling with tasty-golden under Windows 10 (2004)

### ISSUE THREAD

**Issue by jrp2014** [feuerbach/tasty-golden#42]
I suggest that, to improve the reliability of testing under Windows, you could

* Bump the limits for `System.Process` to 1.6.8.1 (https://github.com/haskell/process/pull/168) and set `use_process_jobs=True` when constructing the `diff` process
* Mention that the `diff` process should not call `exec` as the ExitCode will be unreliable.  (This is a pity as I suspect that `git diff` probably does this.)
* Mention that the test harness should be compiled `-threaded`
 
(I am having stability problems with a test suite on Windows that don't occur on Linux and MacOS.)

**Comment by feuerbach** [comment]
No objections from me — could you send a PR? Ideally with explanations of what each of these does/why they are needed (in the docs for doc changes and in the comments for code changes.)

**Comment by jrp2014** [comment]
Will do.  When you say "docs" what are you referring to?

**Comment by feuerbach** [comment]
I mean your points (2) and (3). E.g. when mentioning that the test harness should be compiled `-threaded`, please also add an explanation on why that's needed (and whether it applies to Windows only).

**Comment by jrp2014** [comment]
Ok, but where should this go? Is there some user-facing documentation somewhere?

**Comment by feuerbach** [comment]
Yes, in the module-level haddocks. There's already some advice there about file names, line endings etc.: https://hackage.haskell.org/package/tasty-golden-2.3.4/docs/Test-Tasty-Golden.html

**Comment by feuerbach** [comment]
Maybe it could also benefit from some headers to establish a bit of structure.

**Comment by jrp2014** [comment]
Sure.  As a side-note. probably a separate issue, there is the question of ctrl-c handling, and whether it should be delegated to the child process.
