### ISSUE TITLE
Update Golden.hs to use more recent System.Process features

### ISSUE THREAD

**Issue by jrp2014** [feuerbach/tasty-golden#44]
Currently, `Golden.hs` uses `CreateProcess` and `hGetContentsStrict` to launch `diff` and collect the results.

We now have available in `System.Process` `withCreateProcess`, `readProcessWithExitCodeSource` etc.

The most obvious way of updating the code (modulo` #ifdef`s) would be something along the lines of
```haskell
        withCreateProcess (proc (head cmd) (tail cmd))
            {   std_out = CreatePipe
              , use_process_jobs = True
            } $ \_sin (Just sout) _serr pid -> do
                  -- strictly read the whole output, so that the process can terminate
                  out <- hGetContentsStrict sout
                  r <- waitForProcess pid
                  return $ case r of
                    ExitSuccess -> Nothing
                    _ -> Just (printf "Test output was different from '%s'. Output of %s:\n" ref (show cmd) <> unpackUtf8 (truncateLargeOutput sizeCutoff out))
```
but it might be preferable to use `readProcessWithExitCodeSource` which does a bit more management.

There is also the issue of how much of the old code to keep in for older versions of `System.Process`.

**Comment by feuerbach** [comment]
Yes, readCreateProcessWithExitCode seems like what we need.

It's included since process-1.2.3.0; could you look up which ghc that was first shipped with and whether any earlier ghc versions fall within our 5 year support policy?

**Comment by jrp2014** [comment]
7.10.1 is the first version to include `readCreateProcessWithExitCode` 
```
1.5.3.18. process
Version number 1.2.3.0 (was 1.2.0.0)
```
https://downloads.haskell.org/~ghc/7.10.3/docs/html/users_guide/release-7-10-1.html#idp46760124817328

So you are missing support for 7.8.4 from Dec 2014.

An alternative approach would be to use `typed-process` https://hackage.haskell.org/package/typed-process which claims to improve over `process` by
* Using type variables to represent the standard streams, making them easier to manipulate
* Use proper concurrency (e.g., the async library) in place of the weird lazy I/O tricks for such things as consuming output streams
* Allow for more complex concurrency by providing STM-based functions
* Using binary I/O correctly
* Providing a more composable API, designed to be easy to use for both simple and complex use cases

Some example usage: https://github.com/fpco/typed-process#readme

https://www.fpcomplete.com/blog/2017/02/typed-process/ makes a fairly compelling case for using it here (eg, no hidden fiddling with bytestring).

It has support for 7.10.1 and 7.8.4 (although the latest version compiles it lacks a build plan for that version).

Either way, it's just going to be a handful of lines of code (and with the latter we can drop `hGetContentsStrict`).

**Comment by feuerbach** [comment]
7.10.1 was released Apr 2015, so that's fine.

**Comment by feuerbach** [comment]
Closing in favor of #46
